### Pandas-DataFrame And Series
Pandas is a powerful data manipulation library in Python, widely used for data analysis and data cleaning. It provides two primary data structures: Series and DataFrame. A Series is a one-dimensional array-like object, while a DataFrame is a two-dimensional, size-mutable, and potentially heterogeneous tabular data structure with labeled axes (rows and columns).

In [1]:
import pandas as pd

In [4]:
## Series
##A Pandas Series is a one-dimensional array-like object that can hold any data type. It is similar to a column in a table.
import pandas as pd

data = [1, 2, 3, 4, 5]
series = pd.Series(data)
print("Series\n", series)
print(type(series))

Series
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.Series'>

In [5]:
# Create a series from a dictionary
data = {
    "a": 1,
    "b": 2,
    "c": 3,
}

series_dict = pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [10]:
data = [10, 20, 30]
index = ["a", "b", "c"]
pd.Series(data, index)

a    10
b    20
c    30
dtype: int64

In [13]:
# Dataframe
# Create a dataframe from a dictionary of list
data = {
    "Name": ["Krish", "John", "Jack"],
    "Age": [25, 30, 45],
    "City": ["Bangalore", "New york", "Florida"],
}
dataframe = pd.DataFrame(data)
print(dataframe)
print(type(dataframe))

    Name  Age       City
0  Krish   25  Bangalore
1   John   30   New york
2   Jack   45    Florida
<class 'pandas.DataFrame'>

In [14]:
import numpy as np

np.array(dataframe)

array([['Krish', 25, 'Bangalore'],
       ['John', 30, 'New york'],
       ['Jack', 45, 'Florida']], dtype=object)

In [16]:
# Create a data frame from a list of Dictionaries

data = [
    {"Name": "Krish", "Age": 32, "City": "Bangalore"},
    {"Name": "John", "Age": 34, "City": "Bangalore"},
    {"Name": "Bappy", "Age": 32, "City": "Bangalore"},
    {"Name": "JAck", "Age": 32, "City": "Bangalore"},
]

dataframe = pd.DataFrame(data)
print(dataframe)
print(type(dataframe))

    Name  Age       City
0  Krish   32  Bangalore
1   John   34  Bangalore
2  Bappy   32  Bangalore
3   JAck   32  Bangalore
<class 'pandas.DataFrame'>

In [19]:
df = pd.read_csv("sales_data.csv")
df.head(5)  # This give me the top 5 records.

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [ ]:
df.tail(5) # the last 5 records

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [ ]:
#  Accessing data from dataframe
data = {
    "Name": ["Krish", "John", "Jack"],
    "Age": [25, 30, 45],
    "City": ["Bangalore", "New york", "Florida"],
}

{'Name': ['Krish', 'John', 'Jack'], 'Age': [25, 30, 45], 'City': ['Bangalore', 'New york', 'Florida']}

In [26]:
dataframe = pd.DataFrame(data)
print(dataframe)

    Name  Age       City
0  Krish   25  Bangalore
1   John   30   New york
2   Jack   45    Florida

In [29]:
dataframe["Name"]

0    Krish
1     John
2     Jack
Name: Name, dtype: str

In [30]:
dataframe.loc[0]

Name        Krish
Age            25
City    Bangalore
Name: 0, dtype: object

In [31]:
dataframe.iloc[0]

Name        Krish
Age            25
City    Bangalore
Name: 0, dtype: object

In [35]:
## Accessing a specified element
dataframe["Name"]

0    Krish
1     John
2     Jack
Name: Name, dtype: str

In [38]:
dataframe

    Name  Age       City
0  Krish   25  Bangalore
1   John   30   New york
2   Jack   45    Florida

In [39]:
dataframe.at[2, "Age"]

np.int64(45)

In [40]:
dataframe.at[2, "Name"]

'Jack'

In [41]:
# Accessing a specified element using iat
dataframe.iat[2, 2]

'Florida'

In [42]:
# Data Manipulation with dataframe

dataframe

    Name  Age       City
0  Krish   25  Bangalore
1   John   30   New york
2   Jack   45    Florida

In [52]:
# Adding a column
dataframe["Salary"] = [5000, 6000, 7000]
dataframe

    Name  Age       City  Salary
0  Krish   25  Bangalore    5000
1   John   30   New york    6000
2   Jack   45    Florida    7000

In [53]:
# removing a column
dataframe.drop("Salary", axis=1)

    Name  Age       City
0  Krish   25  Bangalore
1   John   30   New york
2   Jack   45    Florida

In [54]:
dataframe

    Name  Age       City  Salary
0  Krish   25  Bangalore    5000
1   John   30   New york    6000
2   Jack   45    Florida    7000

In [ ]:
# Here with inplace we removed the col
dataframe.drop("Salary", axis=1, inplace=True)

In [56]:
dataframe

    Name  Age       City
0  Krish   25  Bangalore
1   John   30   New york
2   Jack   45    Florida

In [57]:
# Add Age to the column
dataframe["Age"] = dataframe["Age"] + 1

In [58]:
dataframe

    Name  Age       City
0  Krish   26  Bangalore
1   John   31   New york
2   Jack   46    Florida

In [61]:
dataframe.drop(0, inplace=True)

In [62]:
dataframe

   Name  Age      City
1  John   31  New york
2  Jack   46   Florida

In [63]:
df = pd.read_csv("sales_data.csv")
df.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [64]:
# Display the data types of each column
print("Data types:\n", df.dtypes)

# Describe the DataFrame
print("Statistical summary:\n", df.describe())

Data types:
 Transaction ID        int64
Date                    str
Product Category        str
Product Name            str
Units Sold            int64
Unit Price          float64
Total Revenue       float64
Region                  str
Payment Method          str
dtype: object
Statistical summary:
        Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000

In [65]:
df.describe()

       Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000